public class Exceptionprogram {
		public static void main(String[] args){
			 try {
	            int result = 10 / 0;
	            String str = null;
	            System.out.println(str.length());
	            int[] arr = new int[5];
	            arr[10] = 100;
	        } 
			catch (ArithmeticException e) {
	            System.out.println(e);
	        } 
			catch (NullPointerException e) {
	            System.out.println(e);
	        } 
			catch (ArrayIndexOutOfBoundsException e) {
	            System.out.println(e);
	        }
			 finally {
				 System.out.println("Exception completed");
			 }
			 
	    }
			
